language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql 

script: phpunit --configuration phpunit.xml --coverage-text

# Notifications

matrix:
  allow_failures:

# Notifications

notifications:
  email:
    on_success: change
    on_failure: always

  irc:
    on_success: change
    on_failure: always
    channels:
       - "chat.freenode.net#nitestryker"
    skip_join: true
    template:
      - "Build #%{build_number}: %{repository} %{branch} (%{commit}) %{author} - %{message}"
      - "Build details: %{build_url}"
      - "Code Changes: %{compare_url}"